### ISSUE TITLE
Unable to refresh mapping

### ISSUE THREAD

**Issue by catalinvr** [rfarley3/Kibana#3]
Hello,

Thank you for solving the install issue. My environment uses elasticsearch 2.2 and kibana 4.4.
I want to use your module to update automatically the "logstash-*' index pattern. 

```
root@ip-10-123-208-126:/tmp/Kibana# python -m kibana --refresh 'logstash-*'
Mimicking Kibana GUI refreshFields
Error, couldn't find subkey doc_type[_type]['mapping'][_type]
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/Kibana/kibana/__main__.py", line 98, in <module>
    sys.exit(main())
  File "/tmp/Kibana/kibana/__main__.py", line 89, in main
    return handle_mapping(dotk, map_cmd)
  File "/tmp/Kibana/kibana/__main__.py", line 13, in handle_mapping
    return dotk.do_mapping_refresh()
  File "kibana/dotkibana.py", line 36, in do_mapping_refresh
    return self.mapping.do_refresh()
  File "kibana/mapping.py", line 245, in do_refresh
    es_cache = self.get_field_cache('es')
  File "kibana/mapping.py", line 89, in get_field_cache
    self.get_index_mappings(es_mappings[index_name]['mappings'])
TypeError: 'NoneType' object is not iterable
root@ip-10-123-208-126:/tmp/Kibana# python -m kibana --help
```

Thank you,
Catalin

**Comment by avleen** [comment]
Just a note that I tried to use this too and also had the same problem.
I'll try to look in to it a bit more next week.

**Comment by rfarley3** [comment]
Thanks for finding this! Fixed it.
